In [2]:
import pandas as pd
from IPython.display import display

def extract_mannings_override_region_tables(file_path):
    # Lists for storing data
    region_names, land_use_types, mannings_values, polygon_values = [], [], [], []

    region_name, table_value, polygon_value = "", 0, ""

    with open(file_path, 'r') as file:
        lines = file.readlines()

        i = 0  # Initialize line counter
        while i < len(lines):
            line = lines[i].strip()

            if "LCMann Region Name=" in line:
                region_name = line.split("=")[1]
                i += 1  # Move to the next line
                continue

            if "LCMann Region Table=" in line:
                table_value = int(line.split("=")[1])
                i += 1  # Skip to the next line which starts the table entries
                for j in range(table_value):
                    # Handle multiple commas by splitting from the right
                    land_use, mannings = lines[i+j].rsplit(",", 1)
                    region_names.append(region_name)
                    land_use_types.append(land_use)
                    mannings_values.append(float(mannings))
                    polygon_values.append(polygon_value)  # This will repeat the last polygon_value

                i += table_value  # Skip past the table entries
                continue

            if "LCMann Region Polygon=" in line:
                polygon_value = line.split("=")[1]
                i += 1  # Move to the next line
                continue

            i += 1  # Move to the next line if none of the conditions above are met

    df = pd.DataFrame({
        "Region Name": region_names,
        "Land Use Type": land_use_types,
        "Mannings N Value": mannings_values,
        "Polygon Value": polygon_values
    })

    return df

# File path
ras_2d_geometry_file_path = r"C:\Path\to\your\rasgeometry.g01"

# Extract data
df = extract_mannings_override_region_tables(ras_2d_geometry_file_path)

# Display DataFrame using display function
display(df)

# Write the DataFrame to a CSV file
output_path = r"C:\Path\to\your\RAS2D_Mannings_Tables.csv"  # Change this to your desired path and filename
df.to_csv(output_path, index=False)  # index=False prevents writing row numbers

     Region Name                 Land Use Type  Mannings N Value Polygon Value
0        MC_DG-1                        NoData              0.04
1        MC_DG-1                           255              0.04
2        MC_DG-1                    Open Water              0.04
3        MC_DG-1         Developed, Open Space              0.04
4        MC_DG-1      Developed, Low Intensity              0.04
...          ...                           ...               ...           ...
1967  MC_WNCHV-6          Grassland-Herbaceous              0.24           317
1968  MC_WNCHV-6                   Pasture-Hay              0.24           317
1969  MC_WNCHV-6              Cultivated Crops              0.24           317
1970  MC_WNCHV-6                Woody Wetlands              0.24           317
1971  MC_WNCHV-6  Emergent Herbaceous Wetlands              0.24           317

[1972 rows x 4 columns]